version: '3'
services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pa55w0rd2019"
    ports:
      - "1433:1433"
    volumes:
      - ./ScriptCreateDatabase.sql:/docker-entrypoint-initdb.d/ScriptCreateDatabase.sql

  api01: &api
    image: marisouzas2/bancoapi:latest
    hostname: api01
    ports:
      - "5000:80"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02: 
    <<: *api
    hostname: api02
    ports:
      - "5001:80"
    depends_on:
      - api01
    
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9999:9999" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api02
