name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set Docker tag
      run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV

    - name: Print Directory Content
      run: ls -l

    - name: Build and Push Docker Image
      run: |
        docker build -t marisouzas2/bancoapi:${DOCKER_TAG} -f BancoApi/Dockerfile .
        docker push marisouzas2/bancoapi:${DOCKER_TAG}
